CROSSPATH?=$(M68KTOOLS)/m68k-aout
MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
WDB=$(JAGPATH)/bin/wdb
RDB=$(JAGPATH)/bin/rdbjag
LO=$(JAGPATH)/bin/lo -p $(PARIRQ)
CC=$(CROSSPATH)/bin/gcc
LIB=$(CROSSPATH)/lib/m68000
INCL=$(CROSSPATH)/include
JCP=$(JAGPATH)/bin/jcp

STADDR=4000
ALNFLAGS=-a $(STADDR) x x -rq -v -v -v -w -y $(LIB)
MACFLAGS=-fb -v
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops
